feat: Axis secondaryTick
zakodium/react-plot pull request #267
Opened 2022-01-23 22:26 UTC by wadjih-bencheikh18

closes : https://github.com/zakodium/react-plot/issues/264

2022-01-24 07:13 UTC, targos requested changes
There is something wrong with the implementation. If I put `secondaryTickLength={1}`, the length is the same as the primary ticks (which has a length of 5).

![image](https://user-images.githubusercontent.com/2352663/150737689-03fbacf5-312d-4353-9f75-1e33c7de65c2.png)

2022-01-24 07:13 UTC, targos commented on src/components/Axis/Ticks.tsx
> +    secondaryTickLength = 0,
Default value should be 2

2022-01-24 11:57 UTC, wadjih-bencheikh18 commented on src/components/Axis/Ticks.tsx
> +    secondaryTickLength = 0,
fixed

2022-01-24 12:50 UTC, targos requested changes
https://deploy-preview-267--react-plot.netlify.app/?path=/story/api-parallelaxis--control

Parallel axis should have the same default.

2022-01-24 13:50 UTC, targos commented
Maybe we should use 3 as the default value? With 2 it seems to short to me.

@lpatiny @stropitek wdyt?

2022-01-24 15:58 UTC, stropitek commented
> Maybe we should use 3 as the default value? With 2 it seems to short to me.

Yes I had the same impression when I looked at the stories

2022-01-24 16:04 UTC, wadjih-bencheikh18 commented
default value changed

2022-01-25 07:57 UTC, targos approved these changes
LGTM as a first implementation. We can iterate in other issues/prs if necessary

2022-01-25 07:58 UTC, merged